global:
    host: localhost
    message_router_url: http://msgrouter.att.com:3904
# Missing heartbeats
# Heartbeat interval
# Input topic
# Output topic
# ClosedLoopControlName
vnfs:
    vnfa:
        - 3
        - 60
        - VESCOLL-VNFNJ-SECHEARTBEAT-OUTPUT
        - DCAE-POLICY-HILOTCA-EVENT-OUTPUT
        - ControlLoopEvent1

